blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Report
    url: mailto:code@sadeq.uk
    about: Please report security vulnerabilities privately via email
  - name: General Discussion
    url: https://github.com/sadeqn/sshbian/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/sadeqn/sshbian/blob/main/README.md
    about: Check the README and GUIDELINE for setup and usage information